language: python
dist: xenial # Travis does not support python 3.7 https://github.com/travis-ci/travis-ci/issues/9815
sudo: yes
python:
  - "3.7"
install:
  - ./install.sh
  - pip install coverage
addons:
  sonarcloud:
    organization: "usdot-jpo-ode"
    token:
      secure: $SONAR_TOKEN
    branches:
      - .*
script:
  - coverage run --source=odevalidator setup.py test
  - coverage xml -i
  - sonar-scanner
